=== woonaftl/first-contact/schema/autoBlueprints.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="FTL">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="blueprintList" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>

        <xs:element name="shipBlueprintEnemy" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="class"> <!-- not strict enough -->
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="id" type="xs:string"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="class_elite" minOccurs="0"> <!-- not strict enough -->
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="id" type="xs:string"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="class_pirate" minOccurs="0"> <!-- not strict enough -->
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="id" type="xs:string"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="systemList">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="weapons" minOccurs="0">
                      <xs:complexType>
                        <xs:attribute name="room" type="xs:nonNegativeInteger"/>
                        <xs:attribute name="room_elite" type="xs:nonNegativeInteger"/>
                        <xs:attribute name="room_pirate" type="xs:nonNegativeInteger"/>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="pilot" type="systemTypeSuper" minOccurs="0"/>
                    <xs:element name="doors" type="systemTypeSuper" minOccurs="0"/>
                    <xs:element name="artillery" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="power" type="xs:nonNegativeInteger" use="required"/>
                            <xs:attribute name="max" type="xs:nonNegativeInteger"/>
                            <xs:attribute name="room" type="xs:nonNegativeInteger" use="required"/>
                            <xs:attribute name="room_elite" type="xs:nonNegativeInteger"/>
                            <xs:attribute name="room_pirate" type="xs:nonNegativeInteger"/>
                            <xs:attribute name="weapon" type="xs:string" use="required"/>
                            <xs:attribute name="start" type="xs:boolean" default="true"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="oxygen" type="systemTypeSuper" minOccurs="0"/>
                    <xs:element name="medbay" type="systemTypeSuper" minOccurs="0"/>
                    <xs:element name="clonebay" type="systemTypeSuper" minOccurs="0"/>
                    <xs:element name="teleporter" type="systemTypeSuper" minOccurs="0"/>
                    <xs:element name="drones" minOccurs="0">
                      <xs:complexType>
                        <xs:attribute name="room" type="xs:nonNegativeInteger"/>
                        <xs:attribute name="room_elite" type="xs:nonNegativeInteger"/>
                        <xs:attribute name="room_pirate" type="xs:nonNegativeInteger"/>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="shields" type="systemTypeSuper" minOccurs="0"/>
                    <xs:element name="engines" type="systemTypeSuper" minOccurs="0"/>
                    <xs:element name="cloaking" type="systemTypeSuper" minOccurs="0"/>
                    <xs:element name="hacking" type="systemTypeSuper" minOccurs="0"/>
                    <xs:element name="sensors" type="systemTypeSuper" minOccurs="0"/>
                    <xs:element name="mind" type="systemTypeSuper" minOccurs="0"/>
                    <xs:element name="battery" type="systemTypeSuper" minOccurs="0"/>
                  </xs:all>
                </xs:complexType>
              </xs:element>
              <xs:element name="sector" minOccurs="0" maxOccurs="8">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="weaponList" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="weapon" minOccurs="0" maxOccurs="8">
                            <xs:complexType>
                              <xs:attribute name="name" type="xs:string"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="missiles" type="xs:nonNegativeInteger"/>
                        <xs:attribute name="system_power" type="xs:nonNegativeInteger"/>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="droneList" minOccurs="0"> <!-- not strict enough -->
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="drone" minOccurs="0" maxOccurs="8">
                            <xs:complexType>
                              <xs:attribute name="name" type="xs:string"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="drones" type="xs:nonNegativeInteger"/>
                        <xs:attribute name="system_power" type="xs:nonNegativeInteger"/>
                        <xs:attribute name="count" type="xs:nonNegativeInteger"/>
                        <xs:attribute name="load" type="xs:string"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:nonNegativeInteger"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="health">
                <xs:complexType>
                  <xs:attribute name="amount" type="xs:nonNegativeInteger" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="crewCount">
                <xs:complexType>
                  <xs:attribute name="amount" type="xs:nonNegativeInteger" use="required"/>
                  <xs:attribute name="max" type="xs:nonNegativeInteger" use="required"/>
                  <xs:attribute name="class" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="crewCount_elite" minOccurs="0">
                <xs:complexType>
                  <xs:attribute name="amount" type="xs:nonNegativeInteger" use="required"/>
                  <xs:attribute name="max" type="xs:nonNegativeInteger" use="required"/>
                  <xs:attribute name="class" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="boardingAI" minOccurs="0">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="sabotage"/>
                    <xs:enumeration value="invasion"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="aug" minOccurs="0" maxOccurs="3">
                <xs:complexType>
                  <xs:attribute name="name" type="xs:string"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="cloakImage" type="xs:string" minOccurs="0"/>
              <xs:element name="cloakImage_pirate" type="xs:string" minOccurs="0"/>
              <xs:element name="cloakImage_elite" type="xs:string" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="layout" type="xs:string" use="required"/>
            <xs:attribute name="img" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>

        <xs:element name="shipBlueprint" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="class"> <!-- not strict enough -->
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="id" type="xs:string"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="minSector" type="xs:nonNegativeInteger" minOccurs="0"/>
              <xs:element name="maxSector" type="xs:nonNegativeInteger" minOccurs="0"/>
              <xs:element name="systemList">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="pilot" type="systemType" minOccurs="0"/>
                    <xs:element name="doors" type="systemType" minOccurs="0"/>
                    <xs:element name="artillery" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="power" type="xs:nonNegativeInteger" use="required"/>
                            <xs:attribute name="max" type="xs:nonNegativeInteger"/>
                            <xs:attribute name="room" type="xs:nonNegativeInteger" use="required"/>
                            <xs:attribute name="weapon" type="xs:string" use="required"/>
                            <xs:attribute name="start" type="xs:boolean" default="true"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="oxygen" type="systemType" minOccurs="0"/>
                    <xs:element name="medbay" type="systemType" minOccurs="0"/>
                    <xs:element name="clonebay" type="systemType" minOccurs="0"/>
                    <xs:element name="teleporter" type="systemType" minOccurs="0"/>
                    <xs:element name="drones" type="systemType" minOccurs="0"/>
                    <xs:element name="shields" type="systemType" minOccurs="0"/>
                    <xs:element name="engines" type="systemType" minOccurs="0"/>
                    <xs:element name="weapons" type="systemType" minOccurs="0"/>
                    <xs:element name="cloaking" type="systemType" minOccurs="0"/>
                    <xs:element name="hacking" type="systemType" minOccurs="0"/>
                    <xs:element name="sensors" type="systemType" minOccurs="0"/>
                    <xs:element name="mind" type="systemType" minOccurs="0"/>
                    <xs:element name="battery" type="systemType" minOccurs="0"/>
                  </xs:all>
                </xs:complexType>
              </xs:element>
              <xs:element name="weaponList" minOccurs="0"> <!-- not strict enough -->
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="weapon" minOccurs="0" maxOccurs="8">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="missiles" type="xs:nonNegativeInteger"/>
                  <xs:attribute name="count" type="xs:nonNegativeInteger"/>
                  <xs:attribute name="load" type="xs:string"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="droneList" minOccurs="0"> <!-- not strict enough -->
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="drone" minOccurs="0" maxOccurs="8">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="drones" type="xs:nonNegativeInteger"/>
                  <xs:attribute name="count" type="xs:nonNegativeInteger"/>
                  <xs:attribute name="load" type="xs:string"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="health">
                <xs:complexType>
                  <xs:attribute name="amount" type="xs:nonNegativeInteger" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="maxPower">
                <xs:complexType>
                  <xs:attribute name="amount" type="xs:nonNegativeInteger" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="crewCount">
                <xs:complexType>
                  <xs:attribute name="amount" type="xs:nonNegativeInteger" use="required"/>
                  <xs:attribute name="max" type="xs:nonNegativeInteger" use="required"/>
                  <xs:attribute name="class" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="boardingAI" minOccurs="0">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="sabotage"/>
                    <xs:enumeration value="invasion"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="aug" minOccurs="0" maxOccurs="3">
                <xs:complexType>
                  <xs:attribute name="name" type="xs:string"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="cloakImage" type="xs:string" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="layout" type="xs:string" use="required"/>
            <xs:attribute name="img" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="systemTypeSuper">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="power" type="xs:nonNegativeInteger" use="required"/>
        <xs:attribute name="max" type="xs:nonNegativeInteger"/>
        <xs:attribute name="room" type="xs:nonNegativeInteger" use="required"/>
        <xs:attribute name="room_elite" type="xs:nonNegativeInteger"/>
        <xs:attribute name="room_pirate" type="xs:nonNegativeInteger"/>
        <xs:attribute name="start" type="xs:boolean" default="true"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="systemType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="power" type="xs:nonNegativeInteger" use="required"/>
        <xs:attribute name="max" type="xs:nonNegativeInteger"/>
        <xs:attribute name="room" type="xs:nonNegativeInteger" use="required"/>
        <xs:attribute name="start" type="xs:boolean" default="true"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

</xs:schema>

=== woonaftl/first-contact/data/blueprints/enemies/enemies_pavonian.xml
<?xml version="1.0" encoding="UTF-8"?>
<FTL xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../schema/autoBlueprints.xsd">
  <blueprintList name="SHIPS_PAVONIAN">
    <name>PAVONIAN_ASSAULT</name>
    <name>PAVONIAN_FIGHTER</name>
    <name>PAVONIAN_GUARD</name>
    <name>PAVONIAN_SCOUT</name>
  </blueprintList>

  <!--TODO add 2 generic ships (6) -->

  <shipBlueprintEnemy name="PAVONIAN_ASSAULT" img="pavonian_assault" layout="pavonian_assault">
    <class>Pavonian Assault</class>
    <systemList>
      <pilot power="1" max="3" room="0"/>
      <engines power="1" max="4" room="7"/>
      <weapons room="4"/>
      <oxygen power="1" max="3" room="6"/>
      <shields power="2" max="8" room="9"/>
      <doors power="1" max="3" room="1" start="false"/>
    </systemList>
    <sector id="4">
      <weaponList missiles="1" system_power="6">
        <weapon name="WEAPONS_MISSILES_2"/>
        <weapon name="WEAPONS_CHAIN_3"/>
        <weapon name="WEAPONS_LASER_1"/>
        <weapon name="WEAPONS_LASER_2"/>
      </weaponList>
    </sector>
    <sector id="5">
      <weaponList missiles="1" system_power="7">
        <weapon name="WEAPONS_MISSILES_2"/>
        <weapon name="WEAPONS_CHAIN_3"/>
        <weapon name="WEAPONS_LASER_2"/>
        <weapon name="WEAPONS_LASER_2"/>
      </weaponList>
    </sector>
    <sector id="6">
      <weaponList missiles="1" system_power="8">
        <weapon name="WEAPONS_MISSILES_2"/>
        <weapon name="WEAPONS_CHAIN_3"/>
        <weapon name="WEAPONS_LASER_3"/>
        <weapon name="WEAPONS_LASER_2"/>
      </weaponList>
    </sector>
    <sector id="7">
      <weaponList missiles="2" system_power="8">
        <weapon name="WEAPONS_MISSILES_2"/>
        <weapon name="WEAPONS_CHAIN_3"/>
        <weapon name="WEAPONS_LASER_3"/>
        <weapon name="WEAPONS_LASER_2"/>
      </weaponList>
    </sector>
    <health amount="10"/>
    <crewCount amount="4" max="5" class="pavonian"/>
    <boardingAI>sabotage</boardingAI>
    <aug name="SYSTEM_CASING"/>
    <cloakImage>pavonian_assault</cloakImage>
  </shipBlueprintEnemy>

  <shipBlueprintEnemy name="PAVONIAN_FIGHTER" img="pavonian_fighter" layout="pavonian_fighter">
    <class>Pavonian Fighter</class>
    <systemList>
      <pilot power="1" max="3" room="0"/>
      <engines power="1" max="5" room="6"/>
      <weapons room="1"/>
      <oxygen power="1" max="3" room="7"/>
      <shields power="2" max="8" room="5"/>
      <doors power="1" max="3" room="8" start="false"/>
    </systemList>
    <sector id="1">
      <weaponList missiles="0" system_power="4">
        <weapon name="WEAPONS_CHAIN_2"/>
        <weapon name="WEAPONS_LASER_2"/>
      </weaponList>
    </sector>
    <sector id="2">
      <weaponList missiles="0" system_power="4">
        <weapon name="WEAPONS_CHAIN_2"/>
        <weapon name="WEAPONS_LASER_2"/>
      </weaponList>
    </sector>
    <sector id="3">
      <weaponList missiles="0" system_power="5">
        <weapon name="WEAPONS_CHAIN_2"/>
        <weapon name="WEAPONS_CHAIN_2"/>
        <weapon name="WEAPONS_LASER_1"/>
      </weaponList>
    </sector>
    <sector id="4">
      <weaponList missiles="0" system_power="6">
        <weapon name="WEAPONS_CHAIN_2"/>
        <weapon name="WEAPONS_CHAIN_2"/>
        <weapon name="WEAPONS_LASER_2"/>
      </weaponList>
    </sector>
    <health amount="8"/>
    <crewCount amount="3" max="4" class="pavonian"/>
    <boardingAI>sabotage</boardingAI>
    <aug name="SYSTEM_CASING"/>
    <cloakImage>pavonian_fighter</cloakImage>
  </shipBlueprintEnemy>

  <shipBlueprintEnemy name="PAVONIAN_GUARD" img="pavonian_guard" layout="pavonian_guard">
    <class>Pavonian Guard</class>
    <systemList>
      <pilot power="1" max="3" room="0"/>
      <engines power="1" max="5" room="6"/>
      <weapons room="5"/>
      <oxygen power="1" max="3" room="7"/>
      <shields power="2" max="8" room="4"/>
      <doors power="1" max="3" room="1" start="false"/>
    </systemList>
    <sector id="3">
      <weaponList missiles="1" system_power="5">
        <weapon name="WEAPONS_MISSILES_2"/>
        <weapon name="WEAPONS_CHAIN_2"/>
        <weapon name="WEAPONS_CORE_1"/>
        <weapon name="WEAPONS_CORE_2"/>
      </weaponList>
    </sector>
    <sector id="4">
      <weaponList missiles="1" system_power="6">
        <weapon name="WEAPONS_MISSILES_2"/>
        <weapon name="WEAPONS_CHAIN_3"/>
        <weapon name="WEAPONS_CORE_1"/>
        <weapon name="WEAPONS_CORE_2"/>
      </weaponList>
    </sector>
    <sector id="5">
      <weaponList missiles="1" system_power="7">
        <weapon name="WEAPONS_MISSILES_2"/>
        <weapon name="WEAPONS_CHAIN_3"/>
        <weapon name="WEAPONS_CORE_2"/>
        <weapon name="WEAPONS_CORE_2"/>
      </weaponList>
    </sector>
    <sector id="6">
      <weaponList missiles="1" system_power="8">
        <weapon name="WEAPONS_MISSILES_2"/>
        <weapon name="WEAPONS_CHAIN_3"/>
        <weapon name="WEAPONS_CORE_3"/>
        <weapon name="WEAPONS_CORE_2"/>
      </weaponList>
    </sector>
    <health amount="10"/>
    <crewCount amount="3" max="5" class="pavonian"/>
    <boardingAI>sabotage</boardingAI>
    <aug name="SYSTEM_CASING"/>
    <cloakImage>pavonian_guard</cloakImage>
  </shipBlueprintEnemy>

  <shipBlueprintEnemy name="PAVONIAN_SCOUT" img="pavonian_scout" layout="pavonian_scout">
    <class>Pavonian Scout</class>
    <systemList>
      <pilot power="1" max="3" room="0"/>
      <engines power="1" max="4" room="1"/>
      <weapons room="2"/>
      <oxygen power="1" max="3" room="4"/>
      <shields power="2" max="6" room="5"/>
    </systemList>
    <sector id="0">
      <weaponList missiles="0" system_power="3">
        <weapon name="WEAPONS_CHAIN_2"/>
        <weapon name="WEAPONS_LASER_1"/>
      </weaponList>
    </sector>
    <sector id="1">
      <weaponList missiles="0" system_power="4">
        <weapon name="WEAPONS_CHAIN_2"/>
        <weapon name="WEAPONS_LASER_2"/>
      </weaponList>
    </sector>
    <sector id="2">
      <weaponList missiles="0" system_power="4">
        <weapon name="WEAPONS_CHAIN_2"/>
        <weapon name="WEAPONS_LASER_2"/>
      </weaponList>
    </sector>
    <sector id="3">
      <weaponList missiles="0" system_power="5">
        <weapon name="WEAPONS_CHAIN_2"/>
        <weapon name="WEAPONS_LASER_3"/>
      </weaponList>
    </sector>
    <health amount="7"/>
    <crewCount amount="2" max="3" class="pavonian"/>
    <boardingAI>sabotage</boardingAI>
    <aug name="SYSTEM_CASING"/>
    <cloakImage>pavonian_scout</cloakImage>
  </shipBlueprintEnemy>
</FTL>
