=== woonaftl/first-contact/schema/autoBlueprints.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="FTL">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="blueprintList" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>

        <xs:element name="shipBlueprintEnemy" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="class"> <!-- not strict enough -->
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="id" type="xs:string"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="class_elite" minOccurs="0"> <!-- not strict enough -->
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="id" type="xs:string"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="class_pirate" minOccurs="0"> <!-- not strict enough -->
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="id" type="xs:string"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="systemList">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="weapons" minOccurs="0">
                      <xs:complexType>
                        <xs:attribute name="room" type="xs:nonNegativeInteger"/>
                        <xs:attribute name="room_elite" type="xs:nonNegativeInteger"/>
                        <xs:attribute name="room_pirate" type="xs:nonNegativeInteger"/>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="pilot" type="systemTypeSuper" minOccurs="0"/>
                    <xs:element name="doors" type="systemTypeSuper" minOccurs="0"/>
                    <xs:element name="artillery" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="power" type="xs:nonNegativeInteger" use="required"/>
                            <xs:attribute name="max" type="xs:nonNegativeInteger"/>
                            <xs:attribute name="room" type="xs:nonNegativeInteger" use="required"/>
                            <xs:attribute name="room_elite" type="xs:nonNegativeInteger"/>
                            <xs:attribute name="room_pirate" type="xs:nonNegativeInteger"/>
                            <xs:attribute name="weapon" type="xs:string" use="required"/>
                            <xs:attribute name="start" type="xs:boolean" default="true"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="oxygen" type="systemTypeSuper" minOccurs="0"/>
                    <xs:element name="medbay" type="systemTypeSuper" minOccurs="0"/>
                    <xs:element name="clonebay" type="systemTypeSuper" minOccurs="0"/>
                    <xs:element name="teleporter" type="systemTypeSuper" minOccurs="0"/>
                    <xs:element name="drones" minOccurs="0">
                      <xs:complexType>
                        <xs:attribute name="room" type="xs:nonNegativeInteger"/>
                        <xs:attribute name="room_elite" type="xs:nonNegativeInteger"/>
                        <xs:attribute name="room_pirate" type="xs:nonNegativeInteger"/>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="shields" type="systemTypeSuper" minOccurs="0"/>
                    <xs:element name="engines" type="systemTypeSuper" minOccurs="0"/>
                    <xs:element name="cloaking" type="systemTypeSuper" minOccurs="0"/>
                    <xs:element name="hacking" type="systemTypeSuper" minOccurs="0"/>
                    <xs:element name="sensors" type="systemTypeSuper" minOccurs="0"/>
                    <xs:element name="mind" type="systemTypeSuper" minOccurs="0"/>
                    <xs:element name="battery" type="systemTypeSuper" minOccurs="0"/>
                  </xs:all>
                </xs:complexType>
              </xs:element>
              <xs:element name="sector" minOccurs="0" maxOccurs="8">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="weaponList" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="weapon" minOccurs="0" maxOccurs="8">
                            <xs:complexType>
                              <xs:attribute name="name" type="xs:string"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="missiles" type="xs:nonNegativeInteger"/>
                        <xs:attribute name="system_power" type="xs:nonNegativeInteger"/>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="droneList" minOccurs="0"> <!-- not strict enough -->
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="drone" minOccurs="0" maxOccurs="8">
                            <xs:complexType>
                              <xs:attribute name="name" type="xs:string"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="drones" type="xs:nonNegativeInteger"/>
                        <xs:attribute name="system_power" type="xs:nonNegativeInteger"/>
                        <xs:attribute name="count" type="xs:nonNegativeInteger"/>
                        <xs:attribute name="load" type="xs:string"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:nonNegativeInteger"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="health">
                <xs:complexType>
                  <xs:attribute name="amount" type="xs:nonNegativeInteger" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="crewCount">
                <xs:complexType>
                  <xs:attribute name="amount" type="xs:nonNegativeInteger" use="required"/>
                  <xs:attribute name="max" type="xs:nonNegativeInteger" use="required"/>
                  <xs:attribute name="class" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="crewCount_elite" minOccurs="0">
                <xs:complexType>
                  <xs:attribute name="amount" type="xs:nonNegativeInteger" use="required"/>
                  <xs:attribute name="max" type="xs:nonNegativeInteger" use="required"/>
                  <xs:attribute name="class" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="boardingAI" minOccurs="0">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="sabotage"/>
                    <xs:enumeration value="invasion"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="aug" minOccurs="0" maxOccurs="3">
                <xs:complexType>
                  <xs:attribute name="name" type="xs:string"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="cloakImage" type="xs:string" minOccurs="0"/>
              <xs:element name="cloakImage_pirate" type="xs:string" minOccurs="0"/>
              <xs:element name="cloakImage_elite" type="xs:string" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="layout" type="xs:string" use="required"/>
            <xs:attribute name="img" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>

        <xs:element name="shipBlueprint" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="class"> <!-- not strict enough -->
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="id" type="xs:string"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="minSector" type="xs:nonNegativeInteger" minOccurs="0"/>
              <xs:element name="maxSector" type="xs:nonNegativeInteger" minOccurs="0"/>
              <xs:element name="systemList">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="pilot" type="systemType" minOccurs="0"/>
                    <xs:element name="doors" type="systemType" minOccurs="0"/>
                    <xs:element name="artillery" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="power" type="xs:nonNegativeInteger" use="required"/>
                            <xs:attribute name="max" type="xs:nonNegativeInteger"/>
                            <xs:attribute name="room" type="xs:nonNegativeInteger" use="required"/>
                            <xs:attribute name="weapon" type="xs:string" use="required"/>
                            <xs:attribute name="start" type="xs:boolean" default="true"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="oxygen" type="systemType" minOccurs="0"/>
                    <xs:element name="medbay" type="systemType" minOccurs="0"/>
                    <xs:element name="clonebay" type="systemType" minOccurs="0"/>
                    <xs:element name="teleporter" type="systemType" minOccurs="0"/>
                    <xs:element name="drones" type="systemType" minOccurs="0"/>
                    <xs:element name="shields" type="systemType" minOccurs="0"/>
                    <xs:element name="engines" type="systemType" minOccurs="0"/>
                    <xs:element name="weapons" type="systemType" minOccurs="0"/>
                    <xs:element name="cloaking" type="systemType" minOccurs="0"/>
                    <xs:element name="hacking" type="systemType" minOccurs="0"/>
                    <xs:element name="sensors" type="systemType" minOccurs="0"/>
                    <xs:element name="mind" type="systemType" minOccurs="0"/>
                    <xs:element name="battery" type="systemType" minOccurs="0"/>
                  </xs:all>
                </xs:complexType>
              </xs:element>
              <xs:element name="weaponList" minOccurs="0"> <!-- not strict enough -->
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="weapon" minOccurs="0" maxOccurs="8">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="missiles" type="xs:nonNegativeInteger"/>
                  <xs:attribute name="count" type="xs:nonNegativeInteger"/>
                  <xs:attribute name="load" type="xs:string"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="droneList" minOccurs="0"> <!-- not strict enough -->
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="drone" minOccurs="0" maxOccurs="8">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="drones" type="xs:nonNegativeInteger"/>
                  <xs:attribute name="count" type="xs:nonNegativeInteger"/>
                  <xs:attribute name="load" type="xs:string"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="health">
                <xs:complexType>
                  <xs:attribute name="amount" type="xs:nonNegativeInteger" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="maxPower">
                <xs:complexType>
                  <xs:attribute name="amount" type="xs:nonNegativeInteger" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="crewCount">
                <xs:complexType>
                  <xs:attribute name="amount" type="xs:nonNegativeInteger" use="required"/>
                  <xs:attribute name="max" type="xs:nonNegativeInteger" use="required"/>
                  <xs:attribute name="class" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="boardingAI" minOccurs="0">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="sabotage"/>
                    <xs:enumeration value="invasion"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="aug" minOccurs="0" maxOccurs="3">
                <xs:complexType>
                  <xs:attribute name="name" type="xs:string"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="cloakImage" type="xs:string" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="layout" type="xs:string" use="required"/>
            <xs:attribute name="img" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="systemTypeSuper">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="power" type="xs:nonNegativeInteger" use="required"/>
        <xs:attribute name="max" type="xs:nonNegativeInteger"/>
        <xs:attribute name="room" type="xs:nonNegativeInteger" use="required"/>
        <xs:attribute name="room_elite" type="xs:nonNegativeInteger"/>
        <xs:attribute name="room_pirate" type="xs:nonNegativeInteger"/>
        <xs:attribute name="start" type="xs:boolean" default="true"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="systemType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="power" type="xs:nonNegativeInteger" use="required"/>
        <xs:attribute name="max" type="xs:nonNegativeInteger"/>
        <xs:attribute name="room" type="xs:nonNegativeInteger" use="required"/>
        <xs:attribute name="start" type="xs:boolean" default="true"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

</xs:schema>

=== woonaftl/first-contact/data/blueprints/enemies/enemies_zoltan.xml
<?xml version="1.0" encoding="utf-8"?>
<FTL xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../schema/autoBlueprints.xsd">
  <blueprintList name="SHIPS_ZOLTAN">
    <name>ZOLTAN_FIGHTER</name>
    <name>ZOLTAN_BOMBER</name>
    <name>ENERGY_SCOUT</name>
    <name>ENERGY_RIGGER</name>
    <name>ENERGY_INSTIGATOR</name>
  </blueprintList>
  <blueprintList name="SHIPS_ZOLTAN_PIRATE">
    <name>ZOLTAN_FIGHTER_PIRATE</name>
    <name>ZOLTAN_BOMBER_PIRATE</name>
    <name>ENERGY_SCOUT_PIRATE</name>
    <name>ENERGY_RIGGER_PIRATE</name>
    <name>ENERGY_INSTIGATOR_PIRATE</name>
  </blueprintList>
  <blueprintList name="SHIPS_PIRATE">
    <name>ZOLTAN_FIGHTER_PIRATE</name>
    <name>ZOLTAN_BOMBER_PIRATE</name>
    <name>ENERGY_SCOUT_PIRATE</name>
    <name>ENERGY_RIGGER_PIRATE</name>
    <name>ENERGY_INSTIGATOR_PIRATE</name>
  </blueprintList>

  <!--TODO add 3 generic ships-->

  <shipBlueprintSuper name="ZOLTAN_FIGHTER" layout="energy_fighter" img="energy_fighter">
    <class>Energy Fighter</class>
    <class_pirate>Pirate Fighter</class_pirate>
    <systemList>
      <pilot power="1" max="3" room="5" room_pirate="1"/>
      <doors power="1" max="3" room="2" room_pirate="4" start="false"/>
      <medbay power="1" max="3" room="6" room_pirate="0" start="false"/>
      <oxygen power="1" max="3" room="3" room_pirate="3"/>
      <shields power="2" max="8" room="1" room_pirate="2"/>
      <engines power="1" max="5" room="0" room_pirate="6"/>
      <weapons room="4" room_pirate="5"/>
    </systemList>
    <weaponList sector="1" missiles="0" system_power="4">
      <weapon name="WEAPONS_ION_1"/>
      <weapon name="WEAPONS_BEAM_2"/>
      <weapon name="WEAPONS_ION_1"/>
    </weaponList>
    <weaponList sector="2" missiles="0" system_power="5">
      <weapon name="WEAPONS_ION_1"/>
      <weapon name="WEAPONS_BEAM_3"/>
      <weapon name="WEAPONS_ION_1"/>
    </weaponList>
    <weaponList sector="3" missiles="1" system_power="5">
      <weapon name="WEAPONS_MISSILES_1"/>
      <weapon name="WEAPONS_ION_1"/>
      <weapon name="WEAPONS_BEAM_3"/>
      <weapon name="WEAPONS_ION_1"/>
    </weaponList>
    <weaponList sector="4" missiles="1" system_power="6">
      <weapon name="WEAPONS_MISSILES_1"/>
      <weapon name="WEAPONS_ION_2"/>
      <weapon name="WEAPONS_BEAM_3"/>
      <weapon name="WEAPONS_ION_1"/>
    </weaponList>
    <health amount="7"/>
    <crewCount amount="2" max="3" class="energy"/>
    <boardingAI>sabotage</boardingAI>
    <aug name="ENERGY_SHIELD"/>
    <cloakImage>energy_fighter</cloakImage>
  </shipBlueprintSuper>

  <shipBlueprintSuper name="ZOLTAN_BOMBER" layout="energy_bomber" img="energy_bomber">
    <class>Energy Bomber</class>
    <class_pirate>Pirate Bomber</class_pirate>
    <systemList>
      <pilot power="1" max="3" room="1" room_pirate="0"/>
      <doors power="1" max="3" room="2" room_pirate="6" start="false"/>
      <medbay power="1" max="3" room="6" room_pirate="2" start="false"/>
      <oxygen power="1" max="3" room="5" room_pirate="5"/>
      <shields power="2" max="8" room="3" room_pirate="3"/>
      <engines power="1" max="5" room="7" room_pirate="7"/>
      <drones power="2" max="4" room="0" room_pirate="1" start="false"/>
      <weapons room="4" room_pirate="4"/>
    </systemList>
    <weaponList sector="3" missiles="3" system_power="5">
      <weapon name="WEAPONS_BOMB"/>
      <weapon name="WEAPONS_LASER_2"/>
      <weapon name="WEAPONS_LASER_2"/>
      <weapon name="WEAPONS_ION_1"/>
    </weaponList>
    <weaponList sector="4" missiles="3" system_power="6">
      <weapon name="WEAPONS_BOMB"/>
      <weapon name="WEAPONS_LASER_3"/>
      <weapon name="WEAPONS_LASER_2"/>
      <weapon name="WEAPONS_ION_1"/>
    </weaponList>
    <weaponList sector="5" missiles="3" system_power="7">
      <weapon name="WEAPONS_BOMB"/>
      <weapon name="WEAPONS_LASER_3"/>
      <weapon name="WEAPONS_LASER_3"/>
      <weapon name="WEAPONS_ION_1"/>
    </weaponList>
    <weaponList sector="6" missiles="3" system_power="8">
      <weapon name="WEAPONS_BOMB"/>
      <weapon name="WEAPONS_LASER_4"/>
      <weapon name="WEAPONS_LASER_3"/>
      <weapon name="WEAPONS_ION_1"/>
    </weaponList>
    <droneList drones="3" load="DRONES_COMBAT"/>
    <health amount="7"/>
    <crewCount amount="3" max="6" class="energy"/>
    <boardingAI>sabotage</boardingAI>
    <aug name="ENERGY_SHIELD"/>
    <cloakImage>energy_bomber</cloakImage>
  </shipBlueprintSuper>

  <shipBlueprintSuper name="ENERGY_SCOUT" layout="energy_scout" img="energy_scout">
    <class>Energy Scout</class>
    <class_pirate>Pirate Scout</class_pirate>
    <systemList>
      <pilot power="1" max="2" room="0" room_pirate="0"/>
      <clonebay power="1" max="2" room="3" room_pirate="3" start="false"/>
      <shields power="2" max="4" room="1" room_pirate="2" start="false"/>
      <engines power="1" max="5" room="4" room_pirate="1"/>
      <oxygen power="2" max="3" room="5" room_pirate="6"/>
      <weapons room="2" room_pirate="4"/>
    </systemList>
    <weaponList sector="0" missiles="0" system_power="3">
      <weapon name="WEAPONS_ION_2"/>
      <weapon name="WEAPONS_LASER_1"/>
    </weaponList>
    <weaponList sector="1" missiles="0" system_power="4">
      <weapon name="WEAPONS_ION_2"/>
      <weapon name="WEAPONS_LASER_1"/>
      <weapon name="WEAPONS_LASER_1"/>
    </weaponList>
    <weaponList sector="2" missiles="0" system_power="5">
      <weapon name="WEAPONS_ION_3"/>
      <weapon name="WEAPONS_LASER_1"/>
      <weapon name="WEAPONS_LASER_1"/>
    </weaponList>
    <weaponList sector="3" missiles="1" system_power="5">
      <weapon name="WEAPONS_MISSILES_1"/>
      <weapon name="WEAPONS_ION_3"/>
      <weapon name="WEAPONS_LASER_1"/>
      <weapon name="WEAPONS_LASER_1"/>
    </weaponList>
    <health amount="5"/>
    <crewCount amount="2" max="2" class="energy"/>
    <boardingAI>sabotage</boardingAI>
    <aug name="ENERGY_SHIELD"/>
    <cloakImage>energy_scout</cloakImage>
  </shipBlueprintSuper>

  <shipBlueprintSuper name="ENERGY_INSTIGATOR" layout="energy_instigator" img="energy_instigator">
    <class>Energy Instigator</class>
    <class_pirate>Pirate Instigator</class_pirate>
    <systemList>
      <pilot power="1" max="3" room="0" room_pirate="0"/>
      <clonebay power="1" max="3" room="4" room_pirate="4" start="false"/>
      <shields power="2" max="8" room="6" room_pirate="5"/>
      <engines power="1" max="5" room="2" room_pirate="7"/>
      <oxygen power="1" max="3" room="7" room_pirate="8"/>
      <doors power="1" max="3" room="5" room_pirate="10" start="false"/>
      <mind power="1" room="3" room_pirate="6" start="false"/>
      <weapons room="1" room_pirate="9"/>
    </systemList>
    <weaponList sector="2" missiles="0" system_power="4">
      <weapon name="WEAPONS_BEAM_2"/>
      <weapon name="WEAPONS_ION_1"/>
      <weapon name="WEAPONS_SIMPLE_1"/>
    </weaponList>
    <weaponList sector="3" missiles="0" system_power="5">
      <weapon name="WEAPONS_BEAM_2"/>
      <weapon name="WEAPONS_ION_1"/>
      <weapon name="WEAPONS_SIMPLE_2"/>
    </weaponList>
    <weaponList sector="4" missiles="0" system_power="5">
      <weapon name="WEAPONS_BEAM_2"/>
      <weapon name="WEAPONS_ION_1"/>
      <weapon name="WEAPONS_SIMPLE_2"/>
    </weaponList>
    <weaponList sector="5" missiles="0" system_power="6">
      <weapon name="WEAPONS_BEAM_2"/>
      <weapon name="WEAPONS_ION_2"/>
      <weapon name="WEAPONS_SIMPLE_2"/>
    </weaponList>
    <health amount="6"/>
    <crewCount amount="3" max="5" class="energy"/>
    <boardingAI>sabotage</boardingAI>
    <aug name="ENERGY_SHIELD"/>
    <cloakImage>energy_instigator</cloakImage>
  </shipBlueprintSuper>

  <shipBlueprint name="ZOLTAN_PEACE" layout="energy_peace" img="energy_peace">
    <class>Energy Envoy</class>
    <systemList>
      <pilot power="1" max="3" room="0"/>
      <doors power="1" max="3" room="2" start="false"/>
      <medbay power="1" max="3" room="4" start="false"/>
      <oxygen power="1" max="3" room="3"/>
      <engines power="1" max="5" room="5"/>
    </systemList>
    <health amount="7"/>
    <maxPower amount="3"/>
    <crewCount amount="2" max="3" class="energy"/>
    <boardingAI>sabotage</boardingAI>
  </shipBlueprint>
</FTL>
